name: Update Public Suffix List
on: [push]

env:
  LC_ALL: "en_US.UTF-8"

jobs:
  update-psl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/armeria/armeria/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - uses: actions/checkout@v2

      - id: setup-jdk-19
        name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '19'

      - run: touch starting_updatepsl_SetupGradle_23
      - run: rm starting_updatepsl_SetupGradle_23
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: touch starting_updatepsl_BuildwithGradle_26
      - run: rm starting_updatepsl_BuildwithGradle_26
      - name: Build with Gradle
        run: |
          ./gradlew --no-daemon --stacktrace :core:publicSuffixes

      - run: touch starting_updatepsl_ImportGPGkey_30
      - run: rm starting_updatepsl_ImportGPGkey_30
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSWORD }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - run: touch starting_updatepsl_Pushupdatedpublicsuffixlist_39
      - run: rm starting_updatepsl_Pushupdatedpublicsuffixlist_39
      - name: Push updated public suffix list
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '-S'
          commit_message: Update public suffix list
          file_pattern: core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
          commit_user_name: Meri Kim
          commit_user_email: dl_armeria@linecorp.com
          commit_author: Meri Kim <dl_armeria@linecorp.com>
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - run: cp /home/runner/inotify-logs.csv /home/runner/work/armeria/armeria/optimizing-ci-builds-ci-analysis/
        if: always()
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'Priya-it'
          destination-repository-name: 'ci-analyzes'
          target-branch: 'armeria.1671744188'
          target-directory: 'armeria/1671744188/.github/workflows/public-suffixes/updatepsl'

