name: Publish final artifacts to Maven Central repository

on: [push]

env:
  LC_ALL: "en_US.UTF-8"

jobs:
  publish:
    name: Publish final artifacts
    runs-on: self-hosted
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/armeria/armeria/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - uses: actions/checkout@v2

      - id: setup-jdk-19
        name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '19'

      - run: touch starting_publish_SetupGradle_26
      - run: rm starting_publish_SetupGradle_26
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: touch starting_publish_BuildwithGradle_29
      - run: rm starting_publish_BuildwithGradle_29
      - name: Build with Gradle
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=8 --parallel -PflakyTests=false build
        shell: bash

      - run: touch starting_publish_Publishandcloserepository_34
      - run: rm starting_publish_Publishandcloserepository_34
      - name: Publish and close repository
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=1 publish closeAndReleaseStagingRepository
        env:
          # Should not use '-P' option with 'secrets' that can cause unexpected results
          # if secret values contains white spaces or new lines.
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USER_NAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
        shell: bash
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - run: cp /home/runner/inotify-logs.csv /home/runner/work/armeria/armeria/optimizing-ci-builds-ci-analysis/
        if: always()
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'Priya-it'
          destination-repository-name: 'ci-analyzes'
          target-branch: 'armeria.1671744188'
          target-directory: 'armeria/1671744188/.github/workflows/publish-release/publish'

